name: Experimento 1 - Paralelismo

on:
  push:
    branches: [ "main" ]

jobs:

  IF:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "IF: Fetch de instrucciones"
          sleep 2

  ID:
    needs: IF
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ID: Decodificacion"
          sleep 2

  EX_Inst1:
    needs: ID
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "EX: Ejecutando instruccion 1 en ALU"
          sleep 5

  EX_Inst2:
    needs: ID
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "EX: Ejecutando instruccion 2 en ALU"
          sleep 5

  MEM:
    needs: [EX_Inst1, EX_Inst2]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "MEM: Acceso a memoria"
          sleep 2

  WB:
    needs: MEM
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "WB: Escritura en registros"
          sleep 2
